---
title: "Academic and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

$~$ 

# Education

**Columbia University Mailman School of Public Health** 

MPH in Epidemiology, Certificate in Applied Biostatistics 

New York, NY, September 2018- Present 

Candidate for Graduation: May 2020 

$~$

**Santa Clara University**

Bachelor of Science in Public Health Science and Psychology

Minors: Biology and Psychobiology

Santa Clara, CA, September 2013 - May 2017

$~$ 

# Experience 

**The Janssen Pharmaceutical Companies of Johnson & Johnson**

*Global Market Access Intern*

Raritan, NJ, June 2019 – August 2019 

●	Lead longitudinal qualitative analysis for the Patient Reported Outcomes team for FDA approved drugs with PRO label language and provided recommendations to inform company strategy 

●	Adapted global market access tools for Neuroscience breakthrough therapy for Major Depressive Disorder, Spravato, and incorporated internal stakeholder feedback from Global, Regional, and Local markets

$~$ 

**Zitter Health Insights** 

*Research Analyst, Policy & Access Tracking Tool* (07/17- 04/18)

*Research Analyst, Product Strategies Group* (04/18- 07/18)

San Francisco, CA, July 2017- July 2018

●	Mastered 8+ therapeutic areas, maintaining an error rate of less than 1% and trained secondary team in Mumbai, India

●	Tracked new-to-market drugs leading to widespread client distribution and account team success

●	Researched prior authorization coverage criteria for different therapeutic areas for 500+ insurance payers 

●	Responsible for all client deliverables in the specialty drug landscape (oncology and non-oncology) 

$~$

**Santa Clara County, Department of Health** 

*Student Consultant*

Santa Clara, CA, April 2017 - June 2017 

●	Collaborated with a team of three students to work on our Public Health Senior Capstone Project with SCC DOH to democratize and increase access to the Diabetes Prevention Program (DPP) to its community members 

●	Created deliverables for DOH and stakeholders with ROI calculations for implementing the DPP in the county 

●	Participated in work groups with the DOH and collaborated with local organizations to promote and create education based campaigns to increase awareness to DPP 

$~$

**Neurotrack** 

*Research Operations Intern* 

Redwood City, CA, June 2016 - April 2017 

●	Involved in market research evaluating competitor cognitive health programs while standardizing testing protocols 

●	Performed UI/UX research on Neurotrack’s initial cognitive health program by assessing and deconstructing cognitive psychology principles used 

●	Developed user content for Neurotrack’s website and summarized findings from company’s pilot studies 

$~$ 

**UCSF Dubal Lab** 

*Undergraduate Researcher- Dr. Dena Dubal*

San Francisco, CA, May 2016- January 2017  

●	Compiled a meta-analysis of data obtained from literature about Sex Differences and Mortality in Parkinson’s, Alzheimer’s, Lewy Body Dementia, Fronto-temporal Dementia, and ALS 

●	Skills gained: Cell culture, Western Blot, PCR, qPCR, Mouse Model maintenance, STATA, Graphing and Data Analysis 

$~$ 

**Omada Health** 

*Support Extension* 

San Francisco, CA, August 2015 - December 2016 

●	Collaborated with Omada Health’s Support Team to streamline application processes for their flagship behavioral modification program, resulting in same-day turnover for application analysis using criteria set by the CDC 

●	Participated in outreach calling campaigns targeting certain demographics ranging from 18-65+

$~$ 

**Santa Clara University Engineering World Health- School of Engineering and Frugal Innovation Lab** 

*Public Health Consultant* 

Santa Clara, CA, January 2014- January 2017 

●	Collaborated with Public Health students to perform public health, market, and impact research in developing countries for affordable, portable devices: an EKG and Vitals Sensor created by engineering students for their Senior Design Project 

●	Synthesized constructive feedback on devices from medical and public health professionals to provide to engineering team 

●	Presented Key Findings to University in order to secure funding for students to travel to these developing countries 

$~$ 

# Leadership

**Santa Clara University Office of Undergraduate Admissions**

*Student Ambassador & Leader* 

Santa Clara, CA, October 2013 - June 2017 

●	Communicated with prospective students and families through leading campus wide tours, student panels, and providing front desk assistance

●	Oversaw 50 student employees in a team through the Student Ambassador program specializing in scheduling and outreach visits for high schools and programs throughout the country 

●	Maintained relationships with 75 organizations located over 500-mile radius to advocate higher education to underrepresented high school students to the university

$~$

# Skills

● Microsoft Suite (Access)

● SAS 

● STATA 

● R 

● SQL 

$~$ 

# Languages 
● English (native fluency)

● Tamil (native fluency)


